# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [2]:
print(np.__version__)
np.show_config()

1.24.3
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Akash Tundare/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Akash Tundare/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Akash Tundare/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Akash Tundare/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Akash Tundare/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Akash Tundare/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Akash Tundare/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CB

#### 3. Create a null vector of size 10

In [4]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [8]:
arr = np.array([1,2,3,4,5])
memory_size = arr.nbytes
print(f"Memory size of the array: {memory_size} bytes")

Memory size of the array: 20 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [9]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [10]:
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [12]:
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last)

In [13]:
reversed_vector = vector[::-1]
print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [14]:
arr2 = np.arange(9).reshape(3,3)
print(arr2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [15]:
arr3 = np.array([1,2,0,0,4,0])
indices = np.nonzero(arr3)
print(indices)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix

In [16]:
matrix = np.eye(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [17]:
arr4 = np.random.rand(3,3,3)
print(arr4)

[[[0.95431825 0.15039995 0.62616782]
  [0.86772732 0.18406659 0.76679181]
  [0.55976835 0.11998275 0.54696517]]

 [[0.69473319 0.2735671  0.92092107]
  [0.56928102 0.96218122 0.7640595 ]
  [0.91804802 0.16571203 0.30400933]]

 [[0.86974751 0.41381268 0.45253481]
  [0.17366836 0.79172036 0.10804559]
  [0.89416093 0.32577313 0.12144731]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [21]:
arr5 = np.random.rand(10,10)
mini = np.min(arr5)
maxi = np.max(arr5)
print(arr5)
print("minimum values :", mini)
print("maximum values :", maxi)

[[0.4528503  0.62269899 0.39438936 0.58307694 0.96635435 0.40252664
  0.45327924 0.93337083 0.39198688 0.57282235]
 [0.97572146 0.49336391 0.63008376 0.88234524 0.7961209  0.02704078
  0.08394722 0.77535518 0.24899525 0.84156942]
 [0.366416   0.3813932  0.97382767 0.52241622 0.57433352 0.4598247
  0.94533117 0.13402944 0.7298208  0.3332974 ]
 [0.80261909 0.23016914 0.50155276 0.22665175 0.0961421  0.3004142
  0.31822091 0.35377961 0.18079543 0.19544852]
 [0.55533085 0.91170511 0.79748864 0.92204283 0.56124551 0.84069329
  0.28595203 0.64580683 0.07985877 0.42700399]
 [0.62075757 0.46973553 0.73184648 0.95199621 0.99419541 0.65003745
  0.76727504 0.22630494 0.99605149 0.96853582]
 [0.52013369 0.86561023 0.35880917 0.4633676  0.69011079 0.44501747
  0.77060829 0.56900402 0.08064461 0.318413  ]
 [0.93856612 0.43090079 0.91066357 0.37248304 0.74021303 0.07841971
  0.69570607 0.60148512 0.0381452  0.33993615]
 [0.10108387 0.90448423 0.71479614 0.51301252 0.08250904 0.02759834
  0.66926134 0

#### 14. Create a random vector of size 30 and find the mean value

In [22]:
random_vector = np.random.rand(30)

mean_value = np.mean(random_vector)

print(random_vector)
print("Mean value:", mean_value)

[0.08736863 0.70782707 0.01780001 0.70682432 0.8298949  0.60135234
 0.52476675 0.35918615 0.86680899 0.26504607 0.22251221 0.05172217
 0.6252886  0.1323009  0.55374017 0.90328491 0.08486215 0.67838895
 0.32545022 0.69934134 0.03779252 0.29954683 0.8114114  0.90057378
 0.88195623 0.74913578 0.7390449  0.16246912 0.46326347 0.61719874]
Mean value: 0.4968719867009127


#### 15. Create a 2d array with 1 on the border and 0 inside

In [23]:
size = 5

array = np.zeros((size, size), dtype=int)

array[0, :] = 1  # Top border
array[-1, :] = 1 # Bottom border
array[:, 0] = 1  # Left border
array[:, -1] = 1 # Right border

print(array)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [25]:
first_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])


bordered_array = np.pad(first_array, pad_width=1, mode='constant', constant_values=0)

print("Original array:")
print(first_array)
print("Array with border:")
print(bordered_array)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Array with border:
[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [30]:
matrix = np.zeros((5, 5),dtype=int)

for i in range(1, size):
    matrix[i, i-1] = i

print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [31]:
checkerboard = np.zeros((8, 8), dtype=int)

checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [32]:
shape = (6, 7, 8)

# Calculate the flattened index of the 100th element
flattened_index = 100

# Use np.unravel_index to convert the flattened index to a multidimensional index
index = np.unravel_index(flattened_index, shape)

# Print the multidimensional index
print("Index of the 100th element:", index)

Index of the 100th element: (1, 5, 4)
